package com.jessitron.telephonegame.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.IdentityScopeType;

import com.jessitron.telephonegame.dao.Game;
import com.jessitron.telephonegame.dao.Reading;

import com.jessitron.telephonegame.dao.GameDao;
import com.jessitron.telephonegame.dao.ReadingDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig gameDaoConfig;
    private final DaoConfig readingDaoConfig;

    private final GameDao gameDao;
    private final ReadingDao readingDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        gameDaoConfig = daoConfigMap.get(GameDao.class).clone();
        gameDaoConfig.initIdentityScope(type);

        readingDaoConfig = daoConfigMap.get(ReadingDao.class).clone();
        readingDaoConfig.initIdentityScope(type);

        gameDao = new GameDao(gameDaoConfig, this);
        readingDao = new ReadingDao(readingDaoConfig, this);

        registerDao(Game.class, gameDao);
        registerDao(Reading.class, readingDao);
    }
    
    public void clear() {
        gameDaoConfig.getIdentityScope().clear();
        readingDaoConfig.getIdentityScope().clear();
    }

    public GameDao getGameDao() {
        return gameDao;
    }

    public ReadingDao getReadingDao() {
        return readingDao;
    }

}
